const csd_version = '20/9/2023'
var programma = [
	{
		class: 'ΗΥ-100',
		name: 'Εισαγωγή στην Επιστήμη Υπολογιστών',
		teacher: 'ΠΡΑΤΙΚΑΚΗΣ',
		monday: '',
		tuesday: '4-6 ΑΜΦ ΣΟ',
		wednesday: '',
		thursday: '4-6 ΑΜΦ ΣΟ',
		friday: '2-4 ΑΜΦ ΣΟ (ΦΡΟΝΤ)',
		time_score: 16
	},
	{
		class: 'ΗΥ-108',
		name: 'Αγγλικά Ι',
		teacher: 'ΡΙΖΟΠΟΥΛΟΥ',
		monday: '',
		tuesday: '2-4 Η.204',
		wednesday: '',
		thursday: '12-2 Η.204',
		friday: '',
		time_score: 14
	},
	{
		class: 'ΗΥ-110',
		name: 'Απειροστικός Λογισμός Ι',
		teacher: 'ΤΣΑΓΚΑΤΑΚΗΣ',
		monday: '',
		tuesday: '10-12 ΑΜΦ ΣΟ',
		wednesday: '',
		thursday: '10-12 ΑΜΦ ΣΟ',
		friday: '4-6 ΑΜΦ ΣΟ (ΦΡΟΝΤ)',
		time_score: 10
	},
	{
		class: 'ΗΥ-112',
		name: 'Φυσική Ι',
		teacher: 'ΚΑΦΕΝΤΖΗΣ',
		monday: '10-12 ΑΜΦ ΣΟ',
		tuesday: '',
		wednesday: '10-12 ΑΜΦ ΣΟ',
		thursday: '',
		friday: '10-12 ΑΜΦ ΣΟ (ΦΡΟΝΤ)',
		time_score: 10
	},
	{
		class: 'ΗΥ-118',
		name: '∆ιακριτά Μαθηματικά',
		teacher: 'ΓΕΩΡΓΑΚΟΠΟΥΛΟΣ',
		monday: '4-6 Α.113',
		tuesday: '6-8 Α.113',
		wednesday: '4-6 Α.113',
		thursday: '',
		friday: '',
		time_score: 16
	},
	{
		class: 'ΗΥ-119',
		name: 'Γραμμική Άλγεβρα',
		teacher: 'ΚΟΜΟΝΤΑΚΗΣ',
		monday: '6-8 ΑΜΦ ΣΟ',
		tuesday: '',
		wednesday: '',
		thursday: '6-8 ΑΜΦ ΣΟ',
		friday: '6-8 ΑΜΦ ΣΟ (ΦΡΟΝΤ)',
		time_score: 18
	},
	{
		class: 'ΗΥ-120',
		name: 'Ψηφιακή Σχεδίαση',
		teacher: 'ΚΑΤΕΒΑΙΝΗΣ',
		monday: '12-2 ΑΜΦ ΣΟ',
		tuesday: '',
		wednesday: '12-2 ΑΜΦ ΣΟ',
		thursday: '',
		friday: '12-2 ΑΜΦ ΣΟ',
		time_score: 12
	},
	{
		class: 'ΗΥ-208',
		name: 'Αγγλικά ΙΙΙ',
		teacher: 'ΡΙΖΟΠΟΥΛΟΥ',
		monday: '',
		tuesday: '12-2 Η.204',
		wednesday: '',
		thursday: '2-4 Η.204',
		friday: '',
		time_score: 12
	},
	{
		class: 'ΗΥ-217',
		name: 'Πιθανότητες',
		teacher: 'ΤΣΑΚΑΛΙ∆ΗΣ',
		monday: '10-12 ΑΜΦ Α',
		tuesday: '',
		wednesday: '10-12 ΑΜΦ Α',
		thursday: '',
		friday: '10-12 ΑΜΦ Α (ΦΡΟΝΤ)',
		time_score: 10
	},
	{
		class: 'ΗΥ-240',
		name: '∆ομές ∆εδομένων',
		teacher: 'ΦΑΤΟΥΡΟΥ',
		monday: '',
		tuesday: '2-4 ΑΜΦ ΣΟ',
		wednesday: '',
		thursday: '12-2 ΑΜΦ ΣΟ',
		friday: '12-2 ΑΜΦ Α (ΦΡΟΝΤ)',
		time_score: 14
	},
	{
		class: 'ΗΥ-252',
		name: 'Αντικειμενοστρεφής Προγραμματισμός',
		teacher: 'ΤΖΙΤΖΙΚΑΣ',
		monday: '',
		tuesday: '10-12 ΑΜΦ Α',
		wednesday: '',
		thursday: '10-12 ΑΜΦ Α',
		friday: '4-6 ΑΜΦ Α (ΦΡΟΝΤ)',
		time_score: 10
	},
	{
		class: 'ΗΥ-280',
		name: 'Θεωρία Υπολογισμού',
		teacher: 'ΓΕΩΡΓΑΚΟΠΟΥΛΟΣ',
		monday: '2-4 ΑΜΦ ΣΟ',
		tuesday: '',
		wednesday: '2-4 ΑΜΦ ΣΟ',
		thursday: '',
		friday: '2-4 Α.113 (ΦΡΟΝΤ)',
		time_score: 14
	},
	{
		class: 'ΗΥ-330',
		name: 'Εισαγωγή στη Θεωρία των Τηλεπικοινωνιακών Συστημάτων',
		teacher: 'ΤΡΑΓΑΝΙΤΗΣ /ΠΑΠΑ∆ΑΚΗΣ ΣΤ.',
		monday: '10-12 Α.125',
		tuesday: '',
		wednesday: '',
		thursday: '10-12 Α.125',
		friday: '',
		time_score: 10
	},
	{
		class: 'ΗΥ-335',
		name: '∆ίκτυα Υπολογιστών',
		teacher: 'ΠΑΠΑ∆ΟΠΟΥΛΗ',
		monday: '12-2 ΑΜΦ Α',
		tuesday: '',
		wednesday: '12-2 ΑΜΦ Α',
		thursday: '',
		friday: '12-2 Α.117 (ΦΡΟΝΤ)',
		time_score: 12
	},
	{
		class: 'ΗΥ-345',
		name: 'Λειτουργικά Συστήματα',
		teacher: 'ΜΑΡΚΑΤΟΣ',
		monday: '',
		tuesday: '4-6 ΑΜΦ Α',
		wednesday: '',
		thursday: '4-6 ΑΜΦ Α',
		friday: '2-4 ΑΜΦ Α (ΦΡΟΝΤ)',
		time_score: 16
	},
	{
		class: 'ΗΥ-352',
		name: 'Τεχνολογία Λογισμικού',
		teacher: 'ΣΑΒΒΙ∆ΗΣ',
		monday: '',
		tuesday: '10-12 Α.125 (ΦΡΟΝΤ)',
		wednesday: '10-12 Α.125',
		thursday: '',
		friday: '10-12 Α.125',
		time_score: 10
	},
	{
		class: 'ΗΥ-358',
		name: 'Γραφική',
		teacher: 'ΠΑΠΑΓΙΑΝΝΑΚΗΣ',
		monday: '',
		tuesday: '6-8 ΑΜΦ Α',
		wednesday: '6-8 ΑΜΦ Α (ΦΡΟΝΤ)',
		thursday: '6-8 ΑΜΦ Α',
		friday: '',
		time_score: 18
	},
	{
		class: 'ΗΥ-359',
		name: '∆ιαδικτυοκεντρικός Προγραμματισμός',
		teacher: 'ΤΖΙΤΖΙΚΑΣ/ΜΟΥΝΤΑΝΤΩΝΑΚΗΣ',
		monday: '2-4 Α.113',
		tuesday: '',
		wednesday: '2-4 Α.113 (ΦΡΟΝΤ)',
		thursday: '2-4 Α.113',
		friday: '',
		time_score: 14
	},
	{
		class: 'ΗΥ-360',
		name: 'Αρχεία και Βάσεις ∆εδομένων',
		teacher: 'ΠΛΕΞΟΥΣΑΚΗΣ',
		monday: '4-6 ΑΜΦ Α',
		tuesday: '',
		wednesday: '4-6 ΑΜΦ Α',
		thursday: '',
		friday: '4-6 Α.113 (ΦΡΟΝΤ)',
		time_score: 16
	},
	{
		class: 'ΗΥ-370',
		name: 'Ψηφιακή Επεξεργασία Σημάτων',
		teacher: 'ΣΤΥΛΙΑΝΟΥ',
		monday: '10-12 Α.121 (ΕΡΓ/ΡΙΟ)',
		tuesday: '10-12 Α.113',
		wednesday: '',
		thursday: '10-12 Α.113',
		friday: '',
		time_score: 10
	},
	{
		class: 'ΗΥ-371',
		name: 'Ψηφιακή Επεξεργασία Εικόνων',
		teacher: 'ΚΟΜΟΝΤΑΚΗΣ',
		monday: '',
		tuesday: '6-8 Α.125',
		wednesday: '6-8 Α.125',
		thursday: '',
		friday: '6-8 Α.125 (ΦΡΟΝΤ)',
		time_score: 18
	},
	{
		class: 'ΗΥ-425',
		name: 'Αρχιτεκτονική Υπολογιστικών Συστημάτων',
		teacher: 'ΠΑΠΑΕΥΣΤΑΘΙΟΥ',
		monday: '2-4 Η.204',
		tuesday: '',
		wednesday: '2-4 Η.204',
		thursday: '',
		friday: '2-4 Η.204',
		time_score: 14
	},
	{
		class: 'ΗΥ-436',
		name: '∆ίκτυα Καθοριζόμενα από Λογισμικό',
		teacher: '∆ΗΜΗΤΡΟΠΟΥΛΟΣ',
		monday: '',
		tuesday: '2-4 Α.121',
		wednesday: '',
		thursday: '2-4 Α.121',
		friday: '10-12 Α.121 (ΦΡΟΝΤ)',
		time_score: 14
	},
	{
		class: 'ΗΥ-452',
		name: 'Εισαγωγή στην Επιστήμη και την Τεχνολογία των Υπηρεσιών',
		teacher: 'ΜΑΓΚΟΥΤΗΣ/ΠΛΕΞΟΥΣΑΚΗΣ/ΠΙΤΙΚΑΚΗΣ/ΜΠΙΤΣΑΚΗ/ΖΕΓΚΙΝΗΣ',
		monday: '10-12 Α.113',
		tuesday: '',
		wednesday: '10-12 Α.113',
		thursday: '',
		friday: '2-4 Α.121 (ΦΡΟΝΤ)',
		time_score: 10
	},
	{
		class: 'ΗΥ-454',
		name: 'Τεχνολογία Ανάπτυξης Έξυπνων ∆ιεπαφών και Παιχνιδιών',
		teacher: 'ΣΑΒΒΙ∆ΗΣ',
		monday: '12-2 Α.121',
		tuesday: '12-2 Α.121 (ΦΡΟΝΤ)',
		wednesday: '',
		thursday: '10-12 Α.121',
		friday: '',
		time_score: 12
	},
	{
		class: 'ΗΥ-458',
		name: 'Εισαγωγή στην Κρυπτογραφία',
		teacher: 'ΜΑΡΚΑΤΟΣ/ΜΑΝΙΦΑΒΑΣ',
		monday: '12-2 Α.125',
		tuesday: '',
		wednesday: '',
		thursday: '12-2 Α.125 (ΦΡΟΝΤ)',
		friday: '12-2 Α.125',
		time_score: 12
	},
	{
		class: 'ΗΥ-460',
		name: 'Συστήματα ∆ιαχείρισης Βάσεων ∆εδομένων',
		teacher: 'ΠΙΤΙΚΑΚΗΣ/ΚΟΝ∆ΥΛΑΚΗΣ',
		monday: '4-6 Η.204 (ΦΡΟΝΤ)',
		tuesday: '',
		wednesday: '4-6 Η.204',
		thursday: '',
		friday: '4-6 Η.204',
		time_score: 16
	},
	{
		class: 'ΗΥ-469',
		name: 'Σύγχρονα Θέματα Αλληλεπίδρασης Ανθρώπου- Υπολογιστή',
		teacher: 'ΣΤΕΦΑΝΙ∆ΗΣ/ΛΕΩΝΙ∆ΗΣ',
		monday: '',
		tuesday: '6-8 Η.204',
		wednesday: '',
		thursday: '6-8 Η.204',
		friday: '6-8 Η.204 (ΦΡΟΝΤ)',
		time_score: 18
	},
	{
		class: 'ΗΥ-484',
		name: '∆υναμική Πολύπλοκων ∆ικτύων',
		teacher: 'ΤΟΛΛΗΣ',
		monday: '4-6 Α.125',
		tuesday: '',
		wednesday: '4-6 Α.125',
		thursday: '',
		friday: '12-2 Α.113',
		time_score: 16
	},
	{
		class: 'ΗΥ-487',
		name: 'Εισαγωγή στην Τεχνητή Νοημοσύνη',
		teacher: 'ΤΣΑΜΑΡ∆ΙΝΟΣ/ΠΙΤΙΚΑΚΗΣ',
		monday: '4-6 Α.121',
		tuesday: '4-6 Α.121 (ΦΡΟΝΤ)',
		wednesday: '',
		thursday: '4-6 Α.121',
		friday: '',
		time_score: 16
	},
	{
		class: 'ΗΥ-500',
		name: 'Εισαγωγή στην Ερευνα',
		teacher: 'ΜΕΛΗ ∆ΕΠ ΤΟΥ ΤΜΗΜΑΤΟΣ',
		monday: '',
		tuesday: '',
		wednesday: '',
		thursday: '12-2 Α.113',
		friday: '',
		time_score: 12
	},
	{
		class: 'ΗΥ-508',
		name: 'Τεχνική Συγγραφή στα Αγγλικά',
		teacher: 'ΡΙΖΟΠΟΥΛΟΥ',
		monday: '',
		tuesday: '10-12 Η.204',
		wednesday: '',
		thursday: '10-12 Η.204',
		friday: '',
		time_score: 10
	},
	{
		class: 'ΗΥ-531',
		name: 'Θέματα Θεωρίας Πληροφοριών',
		teacher: 'ΤΡΑΓΑΝΙΤΗΣ',
		monday: '12-2 Η.208',
		tuesday: '',
		wednesday: '12-2 Η.208',
		thursday: '',
		friday: '',
		time_score: 12
	},
	{
		class: 'ΗΥ-539',
		name: 'Προχωρημένα Θέματα σε Ασύρματα ∆ίκτυα και Κινητά Υπολογιστικά Συστήματα',
		teacher: 'ΠΑΠΑ∆ΟΠΟΥΛΗ',
		monday: '6-8 Η.208',
		tuesday: '',
		wednesday: '6-8 Η.208',
		thursday: '',
		friday: '6-8 Η.208 (ΦΡΟΝΤ)',
		time_score: 18
	},
	{
		class: 'ΗΥ-546',
		name: 'Τύποι και Γλώσσες Προγραμματισμού',
		teacher: 'ΠΡΑΤΙΚΑΚΗΣ',
		monday: '4-6 Η.206',
		tuesday: '',
		wednesday: '4-6 Η.206',
		thursday: '',
		friday: '',
		time_score: 16
	},
	{
		class: 'ΗΥ-559',
		name: 'Τεχνολογίες Υποδομών για Υπηρεσίες Μεγάλης Κλίμακας',
		teacher: 'ΜΑΓΚΟΥΤΗΣ',
		monday: '6-8 Α.121',
		tuesday: '',
		wednesday: '6-8 Α.121',
		thursday: '',
		friday: '',
		time_score: 18
	},
	{
		class: 'ΗΥ-561',
		name: '∆ιαχείριση ∆εδομένων στον Παγκόσμιο Ιστό',
		teacher: 'ΤΖΙΤΖΙΚΑΣ',
		monday: '',
		tuesday: '2-4 Α.125',
		wednesday: '',
		thursday: '2-4 Α.125',
		friday: '',
		time_score: 14
	},
	{
		class: 'ΗΥ-573',
		name: 'Μέθοδοι βελτιστοποίησης',
		teacher: 'ΤΣΑΓΚΑΤΑΚΗΣ',
		monday: '10-12 Η.204',
		tuesday: '',
		wednesday: '10-12 Η.204',
		thursday: '',
		friday: '',
		time_score: 10
	},
	{
		class: 'ΗΥ-575',
		name: 'Εργαστήριο Ρομποτικής Πλοήγησης',
		teacher: 'ΤΡΑΧΑΝΙΑΣ',
		monday: '',
		tuesday: '4-6 Η.206',
		wednesday: '',
		thursday: '4-6 Η.206',
		friday: '',
		time_score: 16
	},
	{
		class: 'ΗΥ-577',
		name: 'Μηχανική Μάθηση',
		teacher: 'ΤΣΑΜΑΡ∆ΙΝΟΣ',
		monday: '12-2 Η.204',
		tuesday: '',
		wednesday: '12-2 Η.204',
		thursday: '',
		friday: '12-2 Η.204 (ΦΡΟΝΤ)',
		time_score: 12
	},
	{
		class: 'ΗΥ-578',
		name: 'Επεξεργασία Φωνής',
		teacher: 'ΣΤΥΛΙΑΝΟΥ',
		monday: '2-4 Η.208 (ΦΡΟΝΤ)',
		tuesday: '',
		wednesday: '10-12 Η.208',
		thursday: '',
		friday: '10-12 Η.208',
		time_score: 14
	},
	{
		class: 'ΗΥ-583',
		name: 'Αλγόριθμοι Γράφων',
		teacher: 'ΤΟΛΛΗΣ',
		monday: '12-2 Η.206',
		tuesday: '',
		wednesday: '12-2 Η.206',
		thursday: '',
		friday: '2-4 Η.206 (ΦΡΟΝΤ)',
		time_score: 12
	},
	{
		class: 'ΗΥ-590.72',
		name: 'Introduction to Bioinformatics for Computer Scientists',
		teacher: 'ΣΤΑΜΑΤΑΚΗΣ',
		monday: '9:45-12:15 Κ.206',
		tuesday: '',
		wednesday: '',
		thursday: '',
		friday: '',
		time_score: 9
	},
	{
		class: 'ΗΥ-647',
		name: 'Σύγχρονα Συστήματα Αποθήκευσης ∆εδομένων',
		teacher: 'ΜΠΙΛΑΣ/ΣΑΛΟΥΣΤΡΟΣ',
		monday: '10-12 Ε.313',
		tuesday: '',
		wednesday: '10-12 Ε.313',
		thursday: '',
		friday: '10-12 Ε.313',
		time_score: 10
	},
	{
		class: 'ΗΥ-672',
		name: 'Προχωρημένα Θέματα Υπολογιστικής Όρασης',
		teacher: 'ΑΡΓΥΡΟΣ',
		monday: '',
		tuesday: '2-4 Ε.311',
		wednesday: '',
		thursday: '2-4 Ε.311',
		friday: '',
		time_score: 14
	},
]
